const matches = [
  {id:'mex-rsa', date:'Čt 11. června', time:'21:00', home:'Mexiko', away:'Jižní Afrika', hf:'🇲🇽', af:'🇿🇦'},
  {id:'kor-eur', date:'Pá 12. června', time:'03:00', home:'Jižní Korea', away:'Evropa A', hf:'🇰🇷', af:'🇪🇺'},
  {id:'can-eur', date:'Pá 12. června', time:'21:00', home:'Kanada', away:'Evropa B', hf:'🇨🇦', af:'🇪🇺'},
  {id:'usa-par', date:'So 13. června', time:'00:00', home:'USA', away:'Paraguay', hf:'🇺🇸', af:'🇵🇾'}
];
const bonuses = [
  {id:'champion', question:'Kdo se stane mistrem světa 2026?', points:5, options:['Vyber tým','Argentina','Brazílie','Česko','Francie','Německo','Španělsko']},
  {id:'top-scorer', question:'Kdo bude nejlepším střelcem turnaje?', points:3, options:['Vyber hráče','Kylian Mbappé','Erling Haaland','Harry Kane','Lionel Messi','Vinícius Júnior']}
];
const initialParticipants=[{name:'Jakub Král',token:'jakub-kral-a8f2',submitted:true},{name:'Tereza Malá',token:'tereza-mala-91c4',submitted:false},{name:'David Novotný',token:'david-novotny-7be1',submitted:false},{name:'Anna Veselá',token:'anna-vesela-3d90',submitted:false}];
const getParticipants=()=>JSON.parse(localStorage.getItem('tipLigaParticipants')||JSON.stringify(initialParticipants));
const setParticipants=p=>localStorage.setItem('tipLigaParticipants',JSON.stringify(p));
const tipsKey='tipLigaTips';
const tips=JSON.parse(localStorage.getItem(tipsKey)||'{}');

const tipsForm=document.querySelector('#tips-form');
tipsForm.innerHTML=matches.map(m=>`<article class="match-card"><div class="match-date"><strong>${m.date}</strong>${m.time} · Skupina A</div><div class="teams"><span class="flag">${m.hf}</span><span>${m.home}</span><span>—</span><span>${m.away}</span><span class="flag">${m.af}</span></div><div class="score-inputs"><input aria-label="${m.home}" name="${m.id}-home" type="number" min="0" max="20" inputmode="numeric" value="${tips[m.id]?.home??''}"><span>:</span><input aria-label="${m.away}" name="${m.id}-away" type="number" min="0" max="20" inputmode="numeric" value="${tips[m.id]?.away??''}"></div></article>`).join('');
document.querySelector('#bonus-list').innerHTML=bonuses.map(b=>`<article class="bonus-card"><header><h3>${b.question}</h3><span class="point">+ ${b.points} bodů</span></header><label for="${b.id}">Tvůj tip</label><select id="${b.id}">${b.options.map(o=>`<option ${tips[b.id]===o?'selected':''}>${o}</option>`).join('')}</select></article>`).join('');

function updateProgress(){let complete=0;matches.forEach(m=>{if(tipsForm.elements[`${m.id}-home`].value!==''&&tipsForm.elements[`${m.id}-away`].value!=='')complete++});bonuses.forEach(b=>{if(document.querySelector(`#${b.id}`).selectedIndex>0)complete++});document.querySelector('#progress-label').textContent=`${complete} / 6`;document.querySelector('#progress-bar').style.width=`${complete/6*100}%`}
document.querySelectorAll('input,select').forEach(el=>el.addEventListener('change',updateProgress));updateProgress();

document.querySelector('#save-tips').addEventListener('click',()=>{matches.forEach(m=>tips[m.id]={home:tipsForm.elements[`${m.id}-home`].value,away:tipsForm.elements[`${m.id}-away`].value});bonuses.forEach(b=>tips[b.id]=document.querySelector(`#${b.id}`).value);localStorage.setItem(tipsKey,JSON.stringify(tips));let p=getParticipants();p[0].submitted=true;setParticipants(p);document.querySelector('#save-status').textContent='Tipy byly právě uloženy';showToast('Tipy bezpečně uloženy. Hodně štěstí!');renderParticipants()});

document.querySelectorAll('.switch-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.switch-btn,.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector(`#${btn.dataset.view}-view`).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}));

function renderParticipants(){const p=getParticipants();document.querySelector('#participant-count').textContent=p.length;document.querySelector('#submission-count').textContent=p.filter(x=>x.submitted).length;document.querySelector('#participants-list').innerHTML=p.map((x,i)=>`<div class="participant"><div class="participant-name"><span>${x.name.split(' ').map(n=>n[0]).join('').slice(0,2)}</span><div><strong>${x.name}</strong><small>tipy.example.cz/?t=${x.token}</small></div></div><em class="submitted ${x.submitted?'':'waiting'}">${x.submitted?'Odevzdáno':'Čeká se'}</em><button class="link-btn" data-copy="${location.origin}${location.pathname}?t=${x.token}">Kopírovat odkaz</button></div>`).join('');document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>{navigator.clipboard?.writeText(b.dataset.copy);showToast('Unikátní odkaz zkopírován')}))}renderParticipants();

const dialog=document.querySelector('#app-dialog'),dialogTitle=document.querySelector('#dialog-title'),dialogFields=document.querySelector('#dialog-fields');
function openDialog(type){const configs={participant:{title:'Přidat účastníka',fields:'<div class="field"><label>Jméno a příjmení</label><input name="name" required placeholder="Např. Petra Nováková"></div><p class="dialog-note">Po uložení automaticky vytvoříme unikátní odkaz bez hesla.</p>'},match:{title:'Přidat zápas',fields:'<div class="field"><label>Domácí tým</label><input required placeholder="Např. Česko"></div><div class="field"><label>Hostující tým</label><input required placeholder="Např. Brazílie"></div><div class="field"><label>Datum a čas výkopu</label><input type="datetime-local" required></div>'},question:{title:'Přidat bonusovou otázku',fields:'<div class="field"><label>Text otázky</label><input required placeholder="Např. Kdo vyhraje skupinu?"></div><div class="field"><label>Počet bodů</label><input type="number" min="1" value="3"></div>'},ranking:{title:'Bodování a žebříček',fields:'<p class="dialog-note">Datový model je připravený na výsledky zápasů, automatický výpočet bodů a živý žebříček. Funkci můžete zapnout po zahájení turnaje.</p>'}};let c=configs[type];dialog.dataset.type=type;dialogTitle.textContent=c.title;dialogFields.innerHTML=c.fields;dialog.showModal()}
document.querySelectorAll('.close-btn,.dialog-cancel').forEach(button=>button.addEventListener('click',()=>dialog.close()));
document.querySelector('#add-participant').onclick=()=>openDialog('participant');document.querySelector('#add-match').onclick=()=>openDialog('match');document.querySelector('#add-question').onclick=()=>openDialog('question');document.querySelector('#open-ranking').onclick=()=>openDialog('ranking');
document.querySelector('#dialog-form').addEventListener('submit',e=>{e.preventDefault();if(dialog.dataset.type==='participant'){const name=new FormData(e.target).get('name');if(!name)return;const token=name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z]+/g,'-').replace(/^-|-$/g,'')+'-'+Math.random().toString(16).slice(2,6);setParticipants([...getParticipants(),{name,token,submitted:false}]);renderParticipants()}dialog.close();showToast('Změna byla uložena')});

document.querySelector('#export-btn').addEventListener('click',()=>{const rows=[['Účastník','Token','Stav',...matches.map(m=>`${m.home}–${m.away}`),...bonuses.map(b=>b.question)],...getParticipants().map((p,i)=>[p.name,p.token,p.submitted?'Odevzdáno':'Čeká',...matches.map(m=>i===0&&tips[m.id]?`${tips[m.id].home}:${tips[m.id].away}`:''),...bonuses.map(b=>i===0?tips[b.id]||'':'')])];const csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='tipy-ms-2026.csv';a.click();showToast('CSV export je připravený')});
function showToast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
